name: Deploy PR docs to Pages

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
    - uses: actions/checkout@v2
      name: Checkout PR
      with:
        persist-credentials: false

    - name: Extract PR number
      run: echo "::set-env name=PR_NUMBER::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

    - uses: actions/setup-node@v1
    - name: Install and Build
      run: |
        yarn install
        SAPPER_APP_BASEPATH=attractions/${{ env.PR_NUMBER }} yarn export --basepath attractions/${{ env.PR_NUMBER }}

    - name: Deploy demo to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: __sapper__/export/attractions
        keep_files: true

    - name: Post docs URL on PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Docs available on https://illright.github.io/attractions/${{ env.PR_NUMBER }}/"
